name: prime_video_pro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_screenutil: ^5.0.0+2 #屏幕和控件高宽设置
  dio: ^4.0.1 #网络请求相关
  json_annotation: ^4.0.1
  json_serializable: ^4.1.2
  cached_network_image: ^3.1.0+1
  pull_to_refresh: ^2.0.0
  video_player: ^2.2.7
  sqflite: ^2.0.0+4
  volume_controller: ^2.0.2
  device_display_brightness: ^0.0.6
  fluttertoast: ^8.0.8
  package_info_plus: ^1.3.0
  rive: ^0.7.33
  sqlite_viewer: ^1.0.5
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.17
  share: ^2.0.4
  flutter: 
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.3
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/riv/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf


