import 'package:flutter/widgets.dart';
class IconFont{
  static const String _family = 'iconfont';
  IconFont._();
  static const IconData icon_huodong = IconData(0xe679, fontFamily: _family);
  static const IconData icon_lianjiewangzhiwangzhan = IconData(0xe61f, fontFamily: _family);
  static const IconData icon_browser = IconData(0xe644, fontFamily: _family);
  static const IconData icon_icon_refresh = IconData(0xe65e, fontFamily: _family);
  static const IconData icon_fenxiangfangshi = IconData(0xed2e, fontFamily: _family);
  static const IconData icon_gengduo = IconData(0xe609, fontFamily: _family);
  static const IconData icon_guanbi = IconData(0xe61c, fontFamily: _family);
  static const IconData icon_chenggong = IconData(0xe603, fontFamily: _family);
  static const IconData icon_shibai = IconData(0xe62b, fontFamily: _family);
  static const IconData icon_jia = IconData(0xe659, fontFamily: _family);
  static const IconData icon_you = IconData(0xe636, fontFamily: _family);
  static const IconData icon_loading = IconData(0xe64f, fontFamily: _family);
  static const IconData icon_tuichuquanping_copy = IconData(0xe643, fontFamily: _family);
  static const IconData icon_quanping_ = IconData(0xe667, fontFamily: _family);
  static const IconData icon_yinliang = IconData(0xe662, fontFamily: _family);
  static const IconData icon_24gf_play = IconData(0xea82, fontFamily: _family);
  static const IconData icon_sudu___ = IconData(0xe602, fontFamily: _family);
  static const IconData icon_jiesuofuben = IconData(0xe606, fontFamily: _family);
  static const IconData icon_suofuben = IconData(0xe608, fontFamily: _family);
  static const IconData icon_liangdu = IconData(0xe854, fontFamily: _family);
  static const IconData icon_shanchutianchong = IconData(0xe68c, fontFamily: _family);
  static const IconData icon_shoucangjia = IconData(0xe600, fontFamily: _family);
  static const IconData icon_lishijilu_copy = IconData(0xe620, fontFamily: _family);
  static const IconData icon_guanyuwomen = IconData(0xe61e, fontFamily: _family);
  static const IconData icon_licensexinxi = IconData(0xe601, fontFamily: _family);
  static const IconData icon_wode_F = IconData(0xe61d, fontFamily: _family);
  static const IconData icon_closefill = IconData(0xe6a6, fontFamily: _family);
  static const IconData icon_clear_l = IconData(0xe616, fontFamily: _family);
  static const IconData icon_home_fill = IconData(0xe7ae, fontFamily: _family);
  static const IconData icon_search = IconData(0xe688, fontFamily: _family);
  static const IconData icon_daoxu = IconData(0xe610, fontFamily: _family);
}